name: Record Streaming

on:
  schedule:
    # Split into two valid cron expressions
    - cron: "50,20 0-15 * * *"  # 6:25 AM to 9:55 PM IST
  workflow_dispatch: # Add manual trigger

jobs:
  record-stream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip" # Enable pip caching for faster dependency installation

      - name: Install VLC dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y vlc

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run recording script
        run: python scripts/stream-recorder.py

      - name: Convert audio to video
        run: |
          python scripts/to-video.py \
            --audio_filepath radio_recordings/latest_recording.mp3 \
            --static_image images/AIR-KOCHI-FM-102.jpg \
            --output_video_directory videos \
            --output_video_name latest_recording.mp4

      - name: Upload video as artifact
        uses: actions/upload-artifact@v4
        with:
          name: latest_recording
          path: videos/latest_recording.mp4

      - name: Set up client secrets
        run: echo "${{ secrets.CLIENT_SECRETS }}" > client_secrets.json

      - name: Upload video to YouTube
        run: |
          python scripts/upload_to_youtube.py \
            --video_file videos/latest_recording.mp4 \
            --title "Latest Recording" \
            --description "This is the latest recording from Akashvani Kochi." \
            --tags "radio,recording,akashvani,kochi"
